### ISSUE TITLE
Improve / expand documentation

### ISSUE THREAD

**Issue by chrissimpkins** [f-actions/font-bakery#22]
@vv-monsalve Will you please have a look at the fontbakery GH Action documentation on the README here and let me know if you feel that there is anything missing + needed based on our conversation earlier this week? Ty!

**Comment by vv-monsalve** [comment]
Hi @chrissimpkins. I’ve been using the actions a little bit more to make a more informed suggestion.

I think some Usage information could be added. Suggested:

```
Usage
In the Actions tab of your repository create a custom workflow an edit the .yml to set the required steps.
Below is an example of a workflow with details on the inputs.
```

In the Example Workflow
It could be helpful to add a # comment next to the `name`, `on`, and `subcommand` options to make it clear from there that those are also customizable (as a visual aid, I know the subcommand is detailed after)

In the Quick Start
Comparing what is in the README with the setup that I have now, I noticed there is no mention to the build step on the Example workflow. For clarity's sake, could it be helpful to either include here one demo build step (with at least a note like “set your build process of the font”) or maybe to provide an entire document as a detailed example of how a configuration could be?. Like the one DaMa uses for statmake https://github.com/daltonmaag/statmake/blob/master/tests/data/TestExternalStylespace.designspace.

Otherwise, I feel it could be some confusion between the warning “Note that these steps require that the fonts are built in your CI workflow before the fontbakery testing steps are executed” and the missing mention to that step on the Example workflow.

**Comment by chrissimpkins** [comment]
Thank you very much for all of these suggestions.  I will get this information worked into the docs.  I really appreciate it!

**Comment by chrissimpkins** [comment]
@vv-monsalve I expanded the README with improved workflow annotations and a bit more detail / clarifications in the quick start section.  I think that I've addressed all of your suggestions here.  I'll close this issue.  Feel free to reopen if you feel that it requires more work.  Tyvm!

**Comment by vv-monsalve** [comment]
Happy to help! Thank you for your guidance through Actions
